
def get_included_property():
    keys = {
        "Domain"
        "Phylum",
        "Class",
        "Order",
        "Family",
        "Genus",
        "Species",
        "Strain",
        "Strain history",
        "Strain designations",
        "Other Species Names",
        "Type Strain",
        "Tmin",
        "Tmax",
        "Tgrowth",
        "ToptMin",
        "ToptMax",
        "Topt.",
        "pHmin",
        "pHmax",
        "pHGrowth",
        "pHOptMin",
        "pHOptMax",
        "pHOpt.",
        "naclMin(mol/L)",
        "naclMax(mol/L)",
        "naclGrowth(mol/L)",
        "nacloptMin(mol/L)",
        "nacloptMax(mol/L)",
        "naclopt.",
        "Rate(h-1)",
        "DoubleTime(h)",
        "Optimal Rate(h-1)",
        "Optimal DoubleTime(h)",
    }
    return keys
